### ISSUE TITLE
Cannot read property 'x' of undefined.

### ISSUE THREAD

**Issue by ekkesa** [lucacalcaterra/risco-mqtt-bridge#29]
I have been receiving this error recently, and the status of the alarm is not reporting, yet it seems to be responding to commands.

Running inside docker.

I orignally thought the issue was related to the multi partition mod, but this happens on the unforked version too. Reference to the first reported issue is [here](https://github.com/lucacalcaterra/risco-mqtt-bridge/issues/7#issuecomment-584223686).

log: 

10-02-2020 17:12:49 debug: polling started...,
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'detectors' of undefined,
    at RiscoPoller.riscoPoller.on (/app/app.js:58:76),
    at emitNone (events.js:106:13),
    at RiscoPoller.emit (events.js:208:7),
    at <anonymous>,
    at process._tickCallback (internal/process/next_tick.js:189:7),
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.,
10-02-2020 17:12:49 debug: Init function for getting data from Cloud completed: OK,
10-02-2020 17:12:49 info: Arming status: partarmed,
10-02-2020 17:12:49 debug: newarmstatus emitted,
10-02-2020 17:12:49 debug: return null, overview empty!,
10-02-2020 17:12:44 debug: ...Overview taken...Response code is 200 and no data error: OK,
10-02-2020 17:12:38 debug: ...Detectors taken...Response code is 200 and no data error: OK,
    at RiscoPoller.init (/app/panelPoller.js:35:10),
10-02-2020 17:12:12 debug: Class Connection Constructor end,
10-02-2020 17:12:12 info: Connected to MQTT Server,
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1),
10-02-2020 17:12:22 debug: ...site and Pin Code sent...Response code is 302: OK,
10-02-2020 17:12:27 debug: ...Cameras taken...Response code is 200 and no data error: OK,
10-02-2020 17:12:33 debug: ...Event History taken...Response code is 200 and no data error: OK,
10-02-2020 17:12:17 debug: Logged...Response code is 302: OK

**Comment by ekkesa** [comment]
I powered down the panel (Removing power adapter and battery) and restarted it - this seems to have addressed the issue. Still strange that the web interface worked, but the container didn't...
