### ISSUE TITLE
Warning with nodeJS after arming all parts

### ISSUE THREAD

**Issue by fab33** [lucacalcaterra/risco-mqtt-bridge#49]
Error message on console (same when disarming parts):

```
01-05-2022 18:27:23 info: Status panel infos arrived
(node:5455) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'parts' of null
    at RiscoPoller.riscoPoller.on (/root/risco-mqtt-bridge/app.js:58:67)
    at emitNone (events.js:106:13)
    at RiscoPoller.emit (events.js:208:7)
    at Timeout.timer.setTimeout [as _onTimeout] (/root/risco-mqtt-bridge/panelPoller.js:53:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:5455) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5455) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lucacalcaterra** [comment]
@fab33  app missing to manage multiple partitions ... i should merge a pr asap...
